name: Atualizar CodeStats

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Limpar workspace
      run: |
        git status
        git reset --hard
        git clean -fd

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Obtém todo o histórico

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install requests

    - name: Gerar resumo do CodeStats
      run: python codestats_summary.py

    - name: Atualizar README.md
      run: |
        START="<!--START_CODESTATS-->"
        END="<!--END_CODESTATS-->"
        CONTENT=$(<codestats.md)
        awk -v s="$START" -v e="$END" -v r="$CONTENT" '
          BEGIN {print_code=1}
          $0 ~ s {print; print r; print_code=0; next}
          $0 ~ e {print_code=1}
          print_code {print}
        ' README.md > temp.md && mv temp.md README.md

    - name: Commit e push seguro
      run: |
        # Configuração do Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Autenticação e sincronização
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch origin main
        git reset --hard origin/main
        
        # Verifica mudanças antes de commitar
        if ! git diff --exit-code README.md >/dev/null; then
          git add README.md
          git commit -m "Atualiza estatísticas do CodeStats [skip ci]"
          
          # Tenta push com fallback
          for i in {1..3}; do
            git push origin main && break || sleep 5
          done
        else
          echo "Nenhuma alteração detectada no README.md"
        fi
